<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="merge"
           tests="4"
           failures="3"
           errors="0"
           skipped="0"
           time="81.884">
    <properties></properties>

            <testcase
                name="test4"
                time="7.620"
                classname="tests.tenant.authentication.api.APISingleStepPasswordTOTP">

            <failure type="java.lang.Exception" message="400  content{&quot;username&quot;: [&quot;The user tom123451@safewalk.training already exists&quot;]}">
                <![CDATA[java.lang.Exception: 400  content{"username": ["The user tom123451@safewalk.training already exists"]}
                utils.UserAPI.createUserLDAP(UserAPI.java:48)utils.UserAPI.resetUser(UserAPI.java:74)tests.tenant.authentication.api.APISingleStepPasswordTOTP.test4(APISingleStepPasswordTOTP.java:102)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:568)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </failure>
    </testcase>
            <testcase
                name="test4"
                time="7.781"
                classname="tests.tenant.authentication.api.APISingleStepPasswordTOTP">

            <failure type="java.lang.Exception" message="400  content{&quot;username&quot;: [&quot;The user tom123451@safewalk.training already exists&quot;]}">
                <![CDATA[java.lang.Exception: 400  content{"username": ["The user tom123451@safewalk.training already exists"]}
                utils.UserAPI.createUserLDAP(UserAPI.java:48)utils.UserAPI.resetUser(UserAPI.java:74)tests.tenant.authentication.api.APISingleStepPasswordTOTP.test4(APISingleStepPasswordTOTP.java:102)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:568)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </failure>
    </testcase>
            <testcase
                name="test4"
                time="7.680"
                classname="tests.tenant.authentication.api.APISingleStepPasswordTOTP">

            <failure type="java.lang.Exception" message="400  content{&quot;username&quot;: [&quot;The user tom123451@safewalk.training already exists&quot;]}">
                <![CDATA[java.lang.Exception: 400  content{"username": ["The user tom123451@safewalk.training already exists"]}
                utils.UserAPI.createUserLDAP(UserAPI.java:48)utils.UserAPI.resetUser(UserAPI.java:74)tests.tenant.authentication.api.APISingleStepPasswordTOTP.test4(APISingleStepPasswordTOTP.java:102)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:568)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </failure>
    </testcase>


            <testcase
                name="test4"
                time="58.803"
                classname="tests.tenant.authentication.api.APISingleStepPasswordTOTP">
            </testcase>
</testsuite>
